services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS: redis
      PORT: "8080"
      DEBUG: "true"
  redis:
    image: "redis:alpine"
    restart: always
